type PageType =
  | "landing"
  | "about"
  | "contact"
  | "faq"
  | "product-showcase"
  | "custom";
type StyleType = "modern" | "minimal" | "bold";

interface LiquidTemplateOptions {
  page_type: string;
  title: string;
  description: string;
  sections?: string[];
  style?: string;
}

const styleVars: Record<
  StyleType,
  { accent: string; radius: string; fontWeight: string; spacing: string }
> = {
  modern: {
    accent: "#6366f1",
    radius: "12px",
    fontWeight: "600",
    spacing: "3rem",
  },
  minimal: {
    accent: "#18181b",
    radius: "4px",
    fontWeight: "400",
    spacing: "2rem",
  },
  bold: {
    accent: "#dc2626",
    radius: "0",
    fontWeight: "800",
    spacing: "4rem",
  },
};

function wrapPage(
  title: string,
  style: StyleType,
  innerHtml: string,
  schemaSettings: Record<string, any>[] = []
): string {
  const v = styleVars[style];
  return `{% comment %}
  ${title} — Generated by Shopify AI Command Center
  Style: ${style}
{% endcomment %}

<style>
  .ai-page {
    --accent: ${v.accent};
    --radius: ${v.radius};
    --fw: ${v.fontWeight};
    --spacing: ${v.spacing};
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    color: #1a1a2e;
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem 1.5rem;
  }
  .ai-page h1 { font-weight: var(--fw); font-size: 2.5rem; line-height: 1.15; margin-bottom: 1rem; }
  .ai-page h2 { font-weight: var(--fw); font-size: 1.75rem; margin-bottom: 0.75rem; }
  .ai-page p { line-height: 1.7; color: #4a4a68; margin-bottom: 1rem; }
  .ai-page .btn-primary {
    display: inline-block; background: var(--accent); color: #fff;
    padding: 0.85rem 2rem; border-radius: var(--radius); text-decoration: none;
    font-weight: 600; transition: opacity 0.2s;
  }
  .ai-page .btn-primary:hover { opacity: 0.88; }
  .ai-page .section { padding: var(--spacing) 0; }
  .ai-page .grid-2 { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 2rem; }
  .ai-page .grid-3 { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1.5rem; }
  .ai-page .card {
    background: #fff; border: 1px solid #e5e7eb; border-radius: var(--radius);
    padding: 2rem; transition: box-shadow 0.2s;
  }
  .ai-page .card:hover { box-shadow: 0 4px 24px rgba(0,0,0,0.06); }
  .ai-page .hero { text-align: center; padding: calc(var(--spacing) * 2) 0; }
  .ai-page .hero p { max-width: 640px; margin: 0 auto 2rem; font-size: 1.15rem; }
  @media (max-width: 768px) {
    .ai-page h1 { font-size: 1.75rem; }
    .ai-page .hero { padding: var(--spacing) 0; }
    .ai-page .grid-2, .ai-page .grid-3 { grid-template-columns: 1fr; }
  }
</style>

<div class="ai-page">
${innerHtml}
</div>

{% schema %}
{
  "name": "${title}",
  "settings": [
    {
      "type": "text",
      "id": "heading",
      "label": "Page Heading",
      "default": "${title}"
    }${schemaSettings.length > 0 ? ",\n    " + schemaSettings.map((s) => JSON.stringify(s)).join(",\n    ") : ""}
  ],
  "presets": [
    {
      "name": "${title}"
    }
  ]
}
{% endschema %}`;
}

function heroSection(title: string, subtitle: string): string {
  return `  <section class="hero section">
    <h1>{{ section.settings.heading | default: "${title}" }}</h1>
    <p>${subtitle}</p>
    <a href="#content" class="btn-primary">Learn More</a>
  </section>`;
}

function featuresSection(features: { title: string; desc: string }[]): string {
  const cards = features
    .map(
      (f) => `      <div class="card">
        <h3 style="margin-bottom:0.5rem;font-weight:var(--fw);">${f.title}</h3>
        <p>${f.desc}</p>
      </div>`
    )
    .join("\n");
  return `  <section class="section" id="content">
    <h2 style="text-align:center;margin-bottom:2rem;">Features</h2>
    <div class="grid-3">
${cards}
    </div>
  </section>`;
}

function ctaSection(text: string, buttonLabel: string): string {
  return `  <section class="section" style="text-align:center;background:linear-gradient(135deg,var(--accent),#8b5cf6);border-radius:var(--radius);padding:3rem;color:#fff;margin-top:2rem;">
    <h2 style="color:#fff;">${text}</h2>
    <a href="/collections/all" class="btn-primary" style="background:#fff;color:var(--accent);margin-top:1rem;">${buttonLabel}</a>
  </section>`;
}

function generateLanding(
  title: string,
  description: string,
  sections: string[],
  style: StyleType
): string {
  let inner = heroSection(title, description);

  if (sections.includes("features") || sections.length === 0) {
    inner += "\n\n" + featuresSection([
      { title: "Fast Shipping", desc: "Free 2-day shipping on all orders over $50." },
      { title: "Quality Guaranteed", desc: "Every product is inspected for the highest standards." },
      { title: "24/7 Support", desc: "Our team is always here to help you." },
    ]);
  }

  if (sections.includes("testimonials") || sections.length === 0) {
    inner += `\n\n  <section class="section">
    <h2 style="text-align:center;margin-bottom:2rem;">What Our Customers Say</h2>
    <div class="grid-2">
      <div class="card">
        <p style="font-style:italic;">"Absolutely love the quality and the fast delivery!"</p>
        <strong>— Happy Customer</strong>
      </div>
      <div class="card">
        <p style="font-style:italic;">"Best shopping experience I've had online."</p>
        <strong>— Loyal Shopper</strong>
      </div>
    </div>
  </section>`;
  }

  if (sections.includes("cta") || sections.length === 0) {
    inner += "\n\n" + ctaSection("Ready to get started?", "Shop Now");
  }

  return wrapPage(title, style, inner, [
    { type: "text", id: "subtitle", label: "Subtitle", default: description },
  ]);
}

function generateAbout(
  title: string,
  description: string,
  _sections: string[],
  style: StyleType
): string {
  const inner = `  <section class="hero section">
    <h1>{{ section.settings.heading | default: "${title}" }}</h1>
    <p>${description}</p>
  </section>

  <section class="section">
    <div class="grid-2">
      <div>
        <h2>Our Story</h2>
        <p>{{ section.settings.story | default: "We started with a simple idea: to create products that make a difference in people's lives. What began as a small passion project has grown into a brand trusted by thousands." }}</p>
      </div>
      <div>
        <h2>Our Mission</h2>
        <p>{{ section.settings.mission | default: "We believe in quality over quantity. Every product we offer is thoughtfully designed, ethically sourced, and built to last." }}</p>
      </div>
    </div>
  </section>

  <section class="section" style="text-align:center;">
    <h2>Our Values</h2>
    <div class="grid-3" style="margin-top:1.5rem;">
      <div class="card"><h3>Integrity</h3><p>We do what's right, always.</p></div>
      <div class="card"><h3>Innovation</h3><p>Constantly improving our products and processes.</p></div>
      <div class="card"><h3>Community</h3><p>Building lasting relationships with our customers.</p></div>
    </div>
  </section>`;

  return wrapPage(title, style, inner, [
    { type: "richtext", id: "story", label: "Our Story" },
    { type: "richtext", id: "mission", label: "Our Mission" },
  ]);
}

function generateContact(
  title: string,
  description: string,
  _sections: string[],
  style: StyleType
): string {
  const inner = `  <section class="hero section">
    <h1>{{ section.settings.heading | default: "${title}" }}</h1>
    <p>${description}</p>
  </section>

  <section class="section">
    <div class="grid-2">
      <div>
        <h2>Get in Touch</h2>
        <div style="margin-top:1rem;">
          <p><strong>Email:</strong> {{ shop.email }}</p>
          <p><strong>Phone:</strong> {{ section.settings.phone | default: "1-800-SHOP" }}</p>
          <p><strong>Address:</strong><br>{{ shop.address1 }}<br>{{ shop.city }}, {{ shop.province }} {{ shop.zip }}</p>
        </div>
      </div>
      <div>
        <form action="/contact" method="post" style="display:flex;flex-direction:column;gap:1rem;">
          <input type="hidden" name="form_type" value="contact">
          <input type="hidden" name="utf8" value="✓">
          <div>
            <label style="display:block;font-weight:600;margin-bottom:0.25rem;">Name</label>
            <input type="text" name="contact[name]" required style="width:100%;padding:0.75rem;border:1px solid #d1d5db;border-radius:var(--radius);">
          </div>
          <div>
            <label style="display:block;font-weight:600;margin-bottom:0.25rem;">Email</label>
            <input type="email" name="contact[email]" required style="width:100%;padding:0.75rem;border:1px solid #d1d5db;border-radius:var(--radius);">
          </div>
          <div>
            <label style="display:block;font-weight:600;margin-bottom:0.25rem;">Message</label>
            <textarea name="contact[body]" rows="5" required style="width:100%;padding:0.75rem;border:1px solid #d1d5db;border-radius:var(--radius);"></textarea>
          </div>
          <button type="submit" class="btn-primary" style="border:none;cursor:pointer;">Send Message</button>
        </form>
      </div>
    </div>
  </section>`;

  return wrapPage(title, style, inner, [
    { type: "text", id: "phone", label: "Phone Number", default: "1-800-SHOP" },
  ]);
}

function generateFaq(
  title: string,
  description: string,
  _sections: string[],
  style: StyleType
): string {
  const faqs = [
    { q: "What is your return policy?", a: "We offer a 30-day money-back guarantee on all products. Simply contact our support team to initiate a return." },
    { q: "How long does shipping take?", a: "Standard shipping takes 3-5 business days. Express shipping is available for 1-2 business day delivery." },
    { q: "Do you ship internationally?", a: "Yes! We ship to over 50 countries worldwide. International shipping typically takes 7-14 business days." },
    { q: "How can I track my order?", a: "Once your order ships, you'll receive a tracking number via email. You can also check your order status in your account." },
    { q: "Can I change or cancel my order?", a: "Orders can be modified or cancelled within 1 hour of placement. After that, please contact our support team." },
  ];

  const faqHtml = faqs
    .map(
      (f) => `    <details style="border:1px solid #e5e7eb;border-radius:var(--radius);padding:1.25rem;margin-bottom:0.75rem;">
      <summary style="cursor:pointer;font-weight:var(--fw);list-style:none;display:flex;justify-content:space-between;align-items:center;">
        ${f.q}
        <span style="font-size:1.25rem;transition:transform 0.2s;">+</span>
      </summary>
      <p style="margin-top:1rem;">${f.a}</p>
    </details>`
    )
    .join("\n");

  const inner = `  <section class="hero section">
    <h1>{{ section.settings.heading | default: "${title}" }}</h1>
    <p>${description}</p>
  </section>

  <section class="section" style="max-width:800px;margin:0 auto;">
${faqHtml}
  </section>

${ctaSection("Still have questions?", "Contact Us")}`;

  return wrapPage(title, style, inner);
}

function generateProductShowcase(
  title: string,
  description: string,
  _sections: string[],
  style: StyleType
): string {
  const inner = `  <section class="hero section">
    <h1>{{ section.settings.heading | default: "${title}" }}</h1>
    <p>${description}</p>
  </section>

  <section class="section">
    <div class="grid-3">
      {% for product in collections.all.products limit:12 %}
        <div class="card" style="text-align:center;">
          {% if product.featured_image %}
            <img src="{{ product.featured_image | image_url: width: 400 }}" alt="{{ product.featured_image.alt }}" style="width:100%;height:240px;object-fit:cover;border-radius:var(--radius);margin-bottom:1rem;" loading="lazy">
          {% endif %}
          <h3 style="margin-bottom:0.25rem;">{{ product.title }}</h3>
          <p style="color:var(--accent);font-weight:700;font-size:1.15rem;margin-bottom:0.5rem;">{{ product.price | money }}</p>
          {% if product.compare_at_price > product.price %}
            <span style="text-decoration:line-through;color:#9ca3af;font-size:0.9rem;">{{ product.compare_at_price | money }}</span>
          {% endif %}
          <div style="margin-top:1rem;">
            <a href="{{ product.url }}" class="btn-primary" style="font-size:0.9rem;padding:0.6rem 1.5rem;">View Product</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>

${ctaSection("Explore our full collection", "View All Products")}`;

  return wrapPage(title, style, inner);
}

function generateCustom(
  title: string,
  description: string,
  sections: string[],
  style: StyleType
): string {
  let inner = heroSection(title, description);

  for (const section of sections) {
    const s = section.toLowerCase();
    if (s === "hero") continue; // already included
    if (s === "features") {
      inner += "\n\n" + featuresSection([
        { title: "Feature One", desc: "Description of your first feature." },
        { title: "Feature Two", desc: "Description of your second feature." },
        { title: "Feature Three", desc: "Description of your third feature." },
      ]);
    } else if (s === "testimonials") {
      inner += `\n\n  <section class="section">
    <h2 style="text-align:center;margin-bottom:2rem;">Testimonials</h2>
    <div class="grid-2">
      <div class="card"><p style="font-style:italic;">"Amazing experience!"</p><strong>— Customer A</strong></div>
      <div class="card"><p style="font-style:italic;">"Highly recommend."</p><strong>— Customer B</strong></div>
    </div>
  </section>`;
    } else if (s === "cta") {
      inner += "\n\n" + ctaSection("Take the next step", "Get Started");
    } else {
      inner += `\n\n  <section class="section">
    <h2>${section}</h2>
    <p>Content for the "${section}" section. Customize this in the theme editor.</p>
  </section>`;
    }
  }

  if (sections.length === 0) {
    inner += "\n\n" + featuresSection([
      { title: "Feature One", desc: "Describe your first feature." },
      { title: "Feature Two", desc: "Describe your second feature." },
      { title: "Feature Three", desc: "Describe your third feature." },
    ]);
    inner += "\n\n" + ctaSection("Get started today", "Shop Now");
  }

  return wrapPage(title, style, inner);
}

export function generateLiquidTemplate(options: LiquidTemplateOptions): string {
  const style = (options.style as StyleType) || "modern";
  const sections = options.sections || [];
  const pageType = options.page_type as PageType;

  switch (pageType) {
    case "landing":
      return generateLanding(options.title, options.description, sections, style);
    case "about":
      return generateAbout(options.title, options.description, sections, style);
    case "contact":
      return generateContact(options.title, options.description, sections, style);
    case "faq":
      return generateFaq(options.title, options.description, sections, style);
    case "product-showcase":
      return generateProductShowcase(options.title, options.description, sections, style);
    case "custom":
    default:
      return generateCustom(options.title, options.description, sections, style);
  }
}
